package com.spoolbear.model.enums;

public enum OrderStatus {
    REQUESTED,
    UNDER_REVIEW,
    REJECTED,
    ON_HOLD,
    AWAITING_APPROVAL,
    QUEUED_FOR_PRINTING,
    PRINTING,
    PRINT_FAILED,
    POST_PROCESSING,
    CREATED,
    CANCELLED,
    READY_TO_SHIP,
    OUT_FOR_DELIVERY,
    DELIVERED,
    CONFIRMED,
    RETURN_REQUESTED,
    RETURNED,
    REPLACEMENT_IN_PROGRESS
}

// printings - REQUESTED,UNDER_REVIEW,REJECTED,AWAITING_APPROVAL,QUEUED_FOR_PRINTING,PRINTING
